sudo: false
dist: trusty

language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules

git:
  submodules: false

install:
  - npm install

script:
  - npm run lint
  - npm run test

branches:
  only:
  - master
  - develop
